"""All user-facing strings in English, Hindi, Spanish, and Japanese.

Written at a low reading level on purpose — the user may be 70+ and stressed
about a letter they don't understand. Calm, concrete, never alarmist."""

from __future__ import annotations

STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "title": "Mystery-Mail Guardian",
        "tagline": "Take a photo of a confusing letter. I will explain it in plain words.",
        "privacy": "Your letter never leaves this device. Everything runs locally on small models.",
        "upload_label": "Take a photo of your letter",
        "language_label": "Language / भाषा / Idioma / 言語",
        "analyze_btn": "📖 Read my letter",
        "read_aloud_btn": "🔊 Read it aloud",
        "audio_label": "Listen",
        "section_what": "What this is",
        "section_worry": "Should you worry?",
        "section_todo": "What to do",
        "worry_low": "This looks like normal mail, but always double-check before paying or replying.",
        "worry_caution": "⚠️ Be careful. This letter has a warning sign often seen in scams:",
        "worry_warning": "🚨 Please be very careful. This letter shows several warning signs often seen in scams:",
        "verify": "Before you pay or reply: contact the company or office through a phone number or "
                  "website you already know and trust — never use the contact details printed in this letter.",
        "disclaimer": "I can make mistakes. For anything important, check with someone you trust.",
        "err_no_image": "Please add a photo of your letter first.",
        "err_unreadable": "I could not read this photo clearly. Please try again with more light, a bit closer.",
        "err_not_document": "This photo does not look like a letter or document. Please take a photo of the letter itself.",
        "err_model": "Something went wrong while reading the letter. Please try once more.",
        "err_no_speech": "Read a letter first, then I can read the result aloud.",
        "waiting": "Your explanation will appear here.",
        "fallback_what": "This looks like {label}.",
        "fact_from": "From:",
        "fact_want": "What they want:",
        "fact_amount": "Amount:",
        "fact_deadline": "Deadline:",
        "fallback_step": "Show this letter to a family member or someone you trust.",
        "analyzing": "Reading your letter…",
        "step1": "Take a photo",
        "step2": "I read it",
        "step3": "Listen",
        "samples_label": "Try an example letter",
    },
    "hi": {
        "title": "Mystery-Mail Guardian",
        "tagline": "किसी भी उलझाने वाली चिट्ठी की फोटो लें। मैं उसे आसान शब्दों में समझाऊँगा।",
        "privacy": "आपकी चिट्ठी इस डिवाइस से बाहर नहीं जाती। सब कुछ छोटे मॉडलों पर, यहीं चलता है।",
        "upload_label": "अपनी चिट्ठी की फोटो लें",
        "language_label": "Language / भाषा / Idioma / 言語",
        "analyze_btn": "📖 मेरी चिट्ठी पढ़ो",
        "read_aloud_btn": "🔊 आवाज़ में सुनाओ",
        "audio_label": "सुनिए",
        "section_what": "यह क्या है",
        "section_worry": "क्या चिंता की बात है?",
        "section_todo": "अब क्या करें",
        "worry_low": "यह सामान्य चिट्ठी लगती है, फिर भी पैसे देने या जवाब देने से पहले हमेशा जाँच लें।",
        "worry_caution": "⚠️ सावधान रहें। इस चिट्ठी में एक ऐसा संकेत है जो अक्सर धोखाधड़ी में दिखता है:",
        "worry_warning": "🚨 बहुत सावधान रहें। इस चिट्ठी में धोखाधड़ी जैसे कई संकेत दिख रहे हैं:",
        "verify": "पैसे देने या जवाब देने से पहले: उस कंपनी या दफ़्तर से उसी नंबर या वेबसाइट पर बात करें "
                  "जिसे आप पहले से जानते और भरोसा करते हैं — इस चिट्ठी में छपे नंबर या पते का इस्तेमाल न करें।",
        "disclaimer": "मुझसे गलती हो सकती है। किसी भी ज़रूरी बात के लिए अपने किसी भरोसेमंद व्यक्ति से ज़रूर पूछें।",
        "err_no_image": "पहले अपनी चिट्ठी की फोटो डालें।",
        "err_unreadable": "मैं इस फोटो को साफ़ नहीं पढ़ पाया। ज़्यादा रोशनी में, थोड़ा पास से दोबारा फोटो लें।",
        "err_not_document": "यह फोटो चिट्ठी या दस्तावेज़ जैसी नहीं लगती। कृपया चिट्ठी की ही फोटो लें।",
        "err_model": "चिट्ठी पढ़ते समय कुछ गड़बड़ हो गई। कृपया एक बार फिर कोशिश करें।",
        "err_no_speech": "पहले कोई चिट्ठी पढ़वाएँ, फिर मैं नतीजा आवाज़ में सुना सकता हूँ।",
        "waiting": "आपकी चिट्ठी की जानकारी यहाँ दिखेगी।",
        "fallback_what": "यह {label} लगती है।",
        "fact_from": "किसने भेजा:",
        "fact_want": "वे क्या चाहते हैं:",
        "fact_amount": "रक़म:",
        "fact_deadline": "आख़िरी तारीख़:",
        "fallback_step": "यह चिट्ठी परिवार के किसी सदस्य या भरोसेमंद व्यक्ति को दिखाएँ।",
        "analyzing": "आपकी चिट्ठी पढ़ रहा हूँ…",
        "step1": "फोटो लें",
        "step2": "मैं पढ़ता हूँ",
        "step3": "सुनिए",
        "samples_label": "एक उदाहरण चिट्ठी आज़माएँ",
    },
    "es": {
        "title": "Mystery-Mail Guardian",
        "tagline": "Tome una foto de una carta confusa. Se la explico en palabras sencillas.",
        "privacy": "Su carta nunca sale de este dispositivo. Todo funciona localmente con modelos pequeños.",
        "upload_label": "Tome una foto de su carta",
        "language_label": "Language / भाषा / Idioma / 言語",
        "analyze_btn": "📖 Leer mi carta",
        "read_aloud_btn": "🔊 Léamela en voz alta",
        "audio_label": "Escuchar",
        "section_what": "Qué es esto",
        "section_worry": "¿Debe preocuparse?",
        "section_todo": "Qué hacer",
        "worry_low": "Parece correo normal, pero verifique siempre antes de pagar o responder.",
        "worry_caution": "⚠️ Tenga cuidado. Esta carta tiene una señal de alerta común en estafas:",
        "worry_warning": "🚨 Tenga mucho cuidado. Esta carta muestra varias señales de alerta comunes en estafas:",
        "verify": "Antes de pagar o responder: contacte a la empresa u oficina por un teléfono o sitio web "
                  "que usted ya conozca y en el que confíe — nunca use los datos de contacto impresos en esta carta.",
        "disclaimer": "Puedo equivocarme. Para cualquier asunto importante, consulte con alguien de confianza.",
        "err_no_image": "Primero agregue una foto de su carta.",
        "err_unreadable": "No pude leer esta foto con claridad. Intente de nuevo con más luz, un poco más cerca.",
        "err_not_document": "Esta foto no parece una carta o documento. Por favor, tome una foto de la carta.",
        "err_model": "Algo salió mal al leer la carta. Inténtelo una vez más.",
        "err_no_speech": "Primero lea una carta; después puedo leerle el resultado en voz alta.",
        "waiting": "Su explicación aparecerá aquí.",
        "fallback_what": "Esto parece {label}.",
        "fact_from": "De:",
        "fact_want": "Qué piden:",
        "fact_amount": "Monto:",
        "fact_deadline": "Fecha límite:",
        "fallback_step": "Muestre esta carta a un familiar o a alguien de confianza.",
        "analyzing": "Leyendo su carta…",
        "step1": "Tome una foto",
        "step2": "Yo la leo",
        "step3": "Escuche",
        "samples_label": "Pruebe una carta de ejemplo",
    },
    "ja": {
        "title": "Mystery-Mail Guardian",
        "tagline": "わかりにくい手紙の写真を撮ってください。やさしい言葉でご説明します。",
        "privacy": "お手紙がこの機器の外に出ることはありません。すべて小さなモデルで、この場で動きます。",
        "upload_label": "手紙の写真を撮ってください",
        "language_label": "Language / भाषा / Idioma / 言語",
        "analyze_btn": "📖 手紙を読んでもらう",
        "read_aloud_btn": "🔊 声で聞く",
        "audio_label": "音声で聞く",
        "section_what": "これは何の手紙?",
        "section_worry": "心配は必要?",
        "section_todo": "これからすること",
        "worry_low": "ふつうの郵便物のようです。それでも、お金を払う前や返事をする前には、必ず確かめてください。",
        "worry_caution": "⚠️ ご注意ください。この手紙には、詐欺によく見られるサインが一つあります:",
        "worry_warning": "🚨 十分にご注意ください。この手紙には、詐欺によく見られるサインがいくつもあります:",
        "verify": "お金を払う前や返事をする前に:ご自分がもともと知っていて信頼できる電話番号やホームページから、"
                  "その会社や役所に確かめてください。この手紙に印刷されている連絡先は使わないでください。",
        "disclaimer": "わたしも間違えることがあります。大事なことは、信頼できる人と確かめてください。",
        "err_no_image": "まず、手紙の写真を入れてください。",
        "err_unreadable": "写真がはっきり読めませんでした。もう少し明るい場所で、少し近づいて、もう一度撮ってください。",
        "err_not_document": "この写真は手紙や書類には見えません。手紙そのものを撮ってください。",
        "err_model": "手紙を読むときに問題が起きました。もう一度お試しください。",
        "err_no_speech": "先に手紙を読ませてください。そのあとで、結果を声でお伝えします。",
        "waiting": "ここに説明が出ます。",
        "fallback_what": "これは{label}のようです。",
        "fact_from": "差出人:",
        "fact_want": "用件:",
        "fact_amount": "金額:",
        "fact_deadline": "期限:",
        "fallback_step": "この手紙を、ご家族や信頼できる人に見せてください。",
        "analyzing": "お手紙を読んでいます…",
        "step1": "写真を撮る",
        "step2": "わたしが読む",
        "step3": "声で聞く",
        "samples_label": "見本の手紙で試す",
    },
}

# Localized short labels for triage.DOC_TYPES, used when the model's own
# explanation is missing/unusable and we synthesize one deterministically.
DOC_TYPE_LABELS: dict[str, dict[str, str]] = {
    "utility_bill": {"en": "an electricity, water, or utility bill",
                     "hi": "बिजली, पानी या किसी सेवा का बिल",
                     "es": "una factura de luz, agua u otro servicio",
                     "ja": "電気・水道などの料金の請求書"},
    "bank": {"en": "a letter from a bank", "hi": "बैंक की चिट्ठी",
             "es": "una carta de un banco", "ja": "銀行からの手紙"},
    "government_tax": {"en": "a letter from the government or tax office",
                       "hi": "सरकार या टैक्स दफ़्तर की चिट्ठी",
                       "es": "una carta del gobierno o de la oficina de impuestos",
                       "ja": "役所や税務署からの手紙"},
    "medical": {"en": "a medical letter", "hi": "इलाज से जुड़ी चिट्ठी",
                "es": "una carta médica", "ja": "医療についての手紙"},
    "insurance": {"en": "an insurance letter", "hi": "बीमे की चिट्ठी",
                  "es": "una carta del seguro", "ja": "保険の手紙"},
    "subscription": {"en": "a subscription or membership letter",
                     "hi": "किसी सदस्यता या सेवा की चिट्ठी",
                     "es": "una carta de suscripción o membresía",
                     "ja": "定期購読や会員サービスの手紙"},
    "charity": {"en": "a donation request", "hi": "दान माँगने वाली चिट्ठी",
                "es": "una solicitud de donación", "ja": "寄付のお願い"},
    "marketing": {"en": "an advertisement", "hi": "एक विज्ञापन", "es": "publicidad",
                  "ja": "広告"},
    "suspected_scam": {"en": "a letter that looks like it could be a scam",
                       "hi": "धोखाधड़ी जैसी दिखने वाली चिट्ठी",
                       "es": "una carta que podría ser una estafa",
                       "ja": "詐欺のおそれがある手紙"},
    "personal": {"en": "a personal letter", "hi": "निजी चिट्ठी",
                 "es": "una carta personal", "ja": "個人的な手紙"},
    "other": {"en": "an official-looking letter",
              "hi": "सरकारी जैसी दिखने वाली चिट्ठी",
              "es": "una carta de aspecto oficial",
              "ja": "公式の書類のように見える手紙"},
}


def doc_type_label(doc_type: str, lang: str) -> str:
    labels = DOC_TYPE_LABELS.get(doc_type, DOC_TYPE_LABELS["other"])
    return labels.get(lang, labels["en"])

# Localized labels for the scam-signal taxonomy in triage.SIGNAL_IDS.
SIGNAL_LABELS: dict[str, dict[str, str]] = {
    "urgency": {
        "en": "It pushes you to act immediately",
        "hi": "यह तुरंत कुछ करने का दबाव डालती है",
        "es": "Le presiona a actuar de inmediato",
        "ja": "今すぐ行動するように急かしています",
    },
    "gift_card_or_crypto": {
        "en": "It asks for payment by gift card or cryptocurrency",
        "hi": "यह गिफ्ट कार्ड या क्रिप्टो से भुगतान माँगती है",
        "es": "Pide pago con tarjetas de regalo o criptomonedas",
        "ja": "ギフトカードや暗号資産での支払いを求めています",
    },
    "wire_transfer": {
        "en": "It asks for a wire or money transfer",
        "hi": "यह वायर ट्रांसफर या मनी ट्रांसफर माँगती है",
        "es": "Pide una transferencia de dinero",
        "ja": "送金や振り込みを求めています",
    },
    "credentials_request": {
        "en": "It asks for passwords, OTP codes, or personal ID numbers",
        "hi": "यह पासवर्ड, OTP या निजी पहचान नंबर माँगती है",
        "es": "Pide contraseñas, códigos OTP o números de identidad",
        "ja": "パスワードやワンタイムパスワード、個人番号などを尋ねています",
    },
    "prize_too_good": {
        "en": "It promises a prize or deal that seems too good to be true",
        "hi": "यह ऐसा इनाम या ऑफ़र देती है जो सच होने के लिए बहुत अच्छा लगता है",
        "es": "Promete un premio u oferta demasiado buena para ser verdad",
        "ja": "話がうますぎる賞品や特典を約束しています",
    },
    "threat_or_arrest": {
        "en": "It threatens fines, arrest, or closing your account",
        "hi": "यह जुर्माने, गिरफ़्तारी या खाता बंद करने की धमकी देती है",
        "es": "Amenaza con multas, arresto o cierre de su cuenta",
        "ja": "罰金や逮捕、口座の停止などで脅しています",
    },
    "sender_mismatch": {
        "en": "The sender's name and contact details do not match",
        "hi": "भेजने वाले का नाम और संपर्क विवरण मेल नहीं खाते",
        "es": "El nombre del remitente y sus datos no coinciden",
        "ja": "差出人の名前と連絡先が合っていません",
    },
    "unofficial_contact": {
        "en": "It tells you to use contact details that skip official channels",
        "hi": "यह आधिकारिक माध्यम छोड़कर दूसरे नंबर या पते पर संपर्क करने को कहती है",
        "es": "Pide usar datos de contacto que evitan los canales oficiales",
        "ja": "正式な窓口を通さない連絡先を使うように言っています",
    },
    "pressure_to_act": {
        "en": "It uses fear or pressure so you do not stop to think",
        "hi": "यह डर या दबाव बनाती है ताकि आप सोच-विचार न कर सकें",
        "es": "Usa miedo o presión para que no lo piense con calma",
        "ja": "考える時間を与えないように、不安や圧力をかけています",
    },
    "lookalike_bill": {
        "en": "It looks like a bill but may be advertising or fake",
        "hi": "यह बिल जैसी दिखती है पर विज्ञापन या नकली हो सकती है",
        "es": "Parece una factura pero puede ser publicidad o falsa",
        "ja": "請求書のように見えますが、広告や偽物かもしれません",
    },
}


def get(lang: str, key: str) -> str:
    """Localized string with English fallback."""
    return STRINGS.get(lang, STRINGS["en"]).get(key, STRINGS["en"].get(key, key))


def signal_label(signal_id: str, lang: str) -> str:
    labels = SIGNAL_LABELS.get(signal_id, {})
    return labels.get(lang, labels.get("en", signal_id))
